version: "3"
services:
  web:
    container_name: dta-web
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ${WEB_STATIC}:/var/www/static/
      - ${WEB_MEDIA}:/var/www/media/
    env_file:
      - .env
    networks:
      - dta_net
    depends_on:
      - db
  db:
    container_name: dta-db
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - dta_db:/var/lib/postgresql/data
    networks:
      - dta_net

volumes:
  dta_db:
networks:
  dta_net: